<a href="https://colab.research.google.com/github/Harish-Arun/ML-Practice/blob/main/Sample_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn import datasets

In [2]:
iris=datasets.load_iris()
X=iris.data
Y=iris.target

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,train_size=0.2)

In [10]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(X_train,Y_train)
pred=knn.predict(X_test)

In [13]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

print("Accuracy Scores ",accuracy_score(Y_test,pred))
print("Classification Report\n",classification_report(Y_test,pred))
print("Confusion Matrix\n",confusion_matrix(Y_test,pred))

Accuracy Scores  0.9416666666666667
Classification Report
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        35
           1       1.00      0.84      0.92        45
           2       0.85      1.00      0.92        40

    accuracy                           0.94       120
   macro avg       0.95      0.95      0.95       120
weighted avg       0.95      0.94      0.94       120

Confusion Matrix
 [[35  0  0]
 [ 0 38  7]
 [ 0  0 40]]
