<a href="https://colab.research.google.com/github/Harish-Arun/ML-Practice/blob/main/Sample_SVM_Linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt

In [3]:
iris=datasets.load_iris()
X=iris.data
Y=iris.target

In [9]:
Y.shape

(150,)

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y)

In [5]:
from sklearn.svm import SVC
clf=SVC(kernel="linear")
clf.fit(X_train,Y_train)

pred=clf.predict(X_test)

In [8]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

print("Accuracy Scores ",accuracy_score(Y_test,pred))
print("Classification Report\n",classification_report(Y_test,pred))
print("Confusion Matrix\n",confusion_matrix(Y_test,pred))

Accuracy Scores  1.0
Classification Report
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        15
           2       1.00      1.00      1.00        10

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38

Confusion Matrix
 [[13  0  0]
 [ 0 15  0]
 [ 0  0 10]]
